//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVPDemo1 {
    
    
    public partial class _Default {
        
        /// <summary>
        /// MD1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MVPDemo1.Controls.MessageDisplay MD1;
        
        /// <summary>
        /// OSS1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MVPDemo1.Controls.OperatorServiceSelect OSS1;
        
        /// <summary>
        /// OD1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MVPDemo1.Controls.OperatorDisplay OD1;
        
        /// <summary>
        /// LoginBySiteID1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MVPDemo1.Controls.LoginBySiteID LoginBySiteID1;
        
        /// <summary>
        /// SiteDisplay1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MVPDemo1.Controls.SiteDisplay SiteDisplay1;
        
        /// <summary>
        /// SS1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MVPDemo1.Controls.SiteSelect SS1;
    }
}
